<script setup>
import { useRouter } from 'vue-router';import BottomNav from '@/components/common/BottomNav.vue';import ExchangeTicket from '@/components/exchange/ExchangeTicket.vue';import { useExchangeStore } from '@/stores/exchange'
const router=useRouter();const exchange=useExchangeStore();const format=(v)=>Number(v||0).toLocaleString('ko-KR',{maximumFractionDigits:2})
</script>
<template><main class="page"><div class="shell"><header><h1>환율·환전</h1></header><nav><button @click="router.push('/exchange')">환율</button><button class="active">환율 알림</button><button @click="router.push('/exchange/banks')">근처 은행</button></nav><ExchangeTicket :title="`등록된 알림 ${exchange.alerts.length}개`" subtitle="목표 환율에 도달하면 바로 알려드려요"/><h2 class="title">내 알림</h2><section class="list"><button v-for="alert in exchange.alerts" :key="alert.id" @click="router.push(`/exchange/alerts/${alert.id}`)"><span>{{ exchange.getCurrency(alert.code)?.flag }}</span><div><b>{{ alert.code }} · {{ exchange.getCurrency(alert.code)?.name }}</b><small>1 {{ alert.code }} = {{ format(alert.target) }}원 이하</small></div><em :class="{off:!alert.enabled}">{{ alert.enabled?'활성':'꺼짐' }}</em><strong>{{ format(alert.amount) }}원</strong><i>›</i></button><div v-if="!exchange.alerts.length" class="empty">등록한 환율 알림이 없어요.</div></section><aside><b>환율이 도달했어요</b><p>EUR가 목표 환율 1,480원에 도달했어요.</p><small>2026.07.25 14:20</small></aside><button class="cta" @click="router.push('/exchange/alerts/new')">＋ 환율 알림 추가</button><BottomNav/></div></main></template>
<style scoped>
.page{min-height:100vh;background:#e7ecf4;color:#10192d}.shell{width:min(100%,390px);min-height:100vh;margin:auto;padding:52px 18px 100px;background:#f7f5ef}header{margin-bottom:16px}header h1{font-size:19px}nav{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:13px}nav button{padding:10px;border-radius:16px;background:#fff;color:#758196;font-size:8px}nav .active{background:#1870e8;color:#fff}.title{margin:20px 2px 8px;font-size:12px}.list button{display:grid;width:100%;grid-template-columns:26px 1fr auto 75px 8px;align-items:center;gap:7px;margin-top:8px;padding:13px;border:1px solid #e1e6ed;border-radius:13px;background:#fff;text-align:left}.list b,.list small{display:block}.list b{font-size:9px}.list small{margin-top:4px;color:#7d899a;font-size:7px}.list em{color:#0a9f73;font-size:7px;font-style:normal}.list em.off{color:#9da7b5}.list strong{text-align:right;color:#174494;font-size:9px}.list i{color:#a2acba;font-size:17px;font-style:normal}.empty{padding:50px;text-align:center;color:#94a3b8;font-size:9px}aside{margin-top:15px;padding:14px;border:1px solid #e1e6ed;border-radius:13px;background:#fff}aside b{font-size:10px}aside p{margin-top:7px;color:#1472ee;font-size:9px}aside small{display:block;margin-top:9px;color:#9ba5b3;font-size:7px}.cta{width:100%;margin-top:14px;padding:14px;border-radius:11px;background:#173f8d;color:#fff;font-weight:900}
.shell :deep(.fixed){display:flex;grid-template-columns:none;gap:0;margin-bottom:0}
</style>
