<script setup>
import { ref } from 'vue';import { useRouter } from 'vue-router';import BottomNav from '@/components/common/BottomNav.vue';import { useExchangeStore } from '@/stores/exchange'
const router=useRouter();const exchange=useExchangeStore();const query=ref('');function open(bank){exchange.selectedBankId=bank.id;router.push(`/exchange/banks/${bank.id}`)}
</script>
<template><main class="page"><div class="shell"><header><h1>환율·환전</h1></header><nav><button @click="router.push('/exchange')">환율</button><button @click="router.push('/exchange/alerts')">환율 알림</button><button class="active">근처 은행</button></nav><label class="search">⌕<input v-model="query" placeholder="지역, 은행명 검색"></label><section class="map"><div class="road one"></div><div class="road two"></div><span class="current">●</span><button v-for="bank in exchange.banks" :key="bank.id" class="marker" :class="{selected:exchange.selectedBankId===bank.id}" :style="{left:`${bank.lat}%`,top:`${bank.top}%`}" @click="exchange.selectedBankId=bank.id">▣</button></section><div class="title"><h2>근처 은행</h2><span>가까운 순</span></div><section class="list"><button v-for="bank in exchange.banks.filter(b=>b.name.includes(query))" :key="bank.id" :class="{selected:exchange.selectedBankId===bank.id}" @click="open(bank)"><i>KB</i><div><b>{{ bank.name }}</b><small>{{ bank.distance }}m · 도보 {{ bank.walk }}분</small></div><em>›</em></button><p v-if="!exchange.banks.filter(b=>b.name.includes(query)).length">검색 결과가 없어요.</p></section><BottomNav/></div></main></template>
<style scoped>
.page{min-height:100vh;background:#e7ecf4;color:#10192d}.shell{width:min(100%,390px);min-height:100vh;margin:auto;padding:52px 18px 100px;background:#f7f5ef}header{margin-bottom:16px}header h1{font-size:19px}nav{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}nav button{padding:10px;border-radius:16px;background:#fff;color:#758196;font-size:8px}nav .active{background:#1870e8;color:#fff}.search{display:flex;gap:8px;padding:11px;border:1px solid #e1e6ed;border-radius:11px;background:#fff;color:#9aa5b5}.search input{flex:1;font-size:8px;outline:none}.map{position:relative;height:230px;margin-top:11px;overflow:hidden;border-radius:14px;background:linear-gradient(30deg,#edf2f4 25%,transparent 25%) 0 0/45px 45px,#dfeaec}.road{position:absolute;background:#fff}.road.one{width:22px;height:130%;left:48%;top:-15%;transform:rotate(5deg)}.road.two{width:130%;height:17px;left:-15%;top:58%;transform:rotate(-12deg)}.current{position:absolute;left:47%;top:48%;z-index:2;display:grid;width:28px;height:28px;place-items:center;border:5px solid #fff;border-radius:50%;background:#1672ed;color:#fff;font-size:8px}.marker{position:absolute;z-index:2;display:grid;width:26px;height:26px;place-items:center;border:3px solid #fff;border-radius:50%;background:#1f61cb;color:#fff;font-size:8px;transform:translate(-50%,-50%)}.marker.selected{width:34px;height:34px;background:#0a9d73}.title{display:flex;justify-content:space-between;margin:18px 2px 8px}.title h2{font-size:12px}.title span{color:#718097;font-size:8px}.list button{display:grid;width:100%;grid-template-columns:34px 1fr 10px;align-items:center;gap:9px;margin-top:8px;padding:12px;border:1px solid #e1e6ed;border-radius:12px;background:#fff;text-align:left}.list button.selected{border-color:#8ebaf4}.list i{display:grid;width:32px;height:32px;place-items:center;border-radius:9px;background:#fff4d2;color:#c98400;font-size:8px;font-style:normal;font-weight:900}.list b,.list small{display:block}.list b{font-size:9px}.list small{margin-top:4px;color:#8995a6;font-size:7px}.list em{color:#9da7b5;font-size:18px;font-style:normal}.list p{padding:40px;text-align:center;color:#94a3b8;font-size:9px}
.shell :deep(.fixed){display:flex;grid-template-columns:none;gap:0;margin-bottom:0}
</style>
