<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { useAssetStore } from '@/stores/asset'
import { useMonthlyFundStore } from '@/stores/monthlyFund'
import { useTravelStore } from '@/stores/travel'
const props=defineProps({modelValue:Boolean,transaction:{type:Object,default:null}}), emit=defineEmits(['update:modelValue','saved'])
const asset=useAssetStore(), fund=useMonthlyFundStore(), travel=useTravelStore(), touched=ref(false)
const form=reactive({name:'',countryCode:'',date:'',amount:'',memo:''})
watch(()=>props.modelValue,open=>{if(!open||!props.transaction)return;const match=props.transaction.date?.match(/(\d{1,2})\/(\d{1,2})/);Object.assign(form,{name:props.transaction.merchant,countryCode:travel.selectedCountryCodes[0]||'',date:match?`2026-${match[1].padStart(2,'0')}-${match[2].padStart(2,'0')}`:'',amount:Number(props.transaction.amount).toLocaleString('ko-KR'),memo:props.transaction.memo||''});touched.value=false})
const amountNumber=computed(()=>Number(String(form.amount).replace(/[^0-9]/g,''))||0), valid=computed(()=>form.name.trim()&&form.countryCode&&form.date&&amountNumber.value>0)
function submit(){touched.value=true;if(!props.transaction||!valid.value||!asset.addPrepaidExpense({...form,icon:'✈️'}))return;fund.updateTransactionCategory(props.transaction.id,'prepaid');emit('saved');emit('update:modelValue',false)}
</script>
<template><Teleport to="body"><div v-if="modelValue" class="wrap" role="dialog" aria-modal="true"><button class="backdrop" type="button" aria-label="닫기" @click="emit('update:modelValue',false)"/><section class="modal"><header><div><h2>여행비 사전지출 등록</h2><p>여행 전에 지불한 항목으로 변경합니다.</p></div><button @click="emit('update:modelValue',false)">×</button></header><label><span>항목명</span><input v-model="form.name" maxlength="40"></label><label><span>국가</span><select v-model="form.countryCode"><option value="" disabled>국가 선택</option><option value="COMMON">🌍 공통 항목</option><option v-for="country in travel.countries" :key="country.code" :value="country.code">{{country.flag}} {{country.name}}</option></select></label><div class="split"><label><span>지출일</span><input v-model="form.date" type="date" readonly></label><label><span>금액</span><input v-model="form.amount" readonly></label></div><label><span>메모</span><textarea v-model="form.memo" maxlength="100" placeholder="메모를 입력해 주세요."/></label><p v-if="touched&&!valid" class="error">필수 정보를 모두 입력해 주세요.</p><button class="save" :disabled="!valid" @click="submit">등록하기</button></section></div></Teleport></template>
<style scoped>
.wrap{position:fixed;inset:0;z-index:110;display:flex;align-items:flex-end;justify-content:center}.backdrop{position:absolute;inset:0;background:#10182780}.modal{position:relative;width:min(100%,430px);max-height:88vh;overflow-y:auto;padding:22px 20px 26px;border-radius:24px 24px 0 0;background:#f8f6f1;color:#151f33}.modal header{display:flex;justify-content:space-between}.modal h2{font-size:20px}.modal header p{margin-top:5px;color:#718096;font-size:10px}.modal header button{font-size:28px;color:#64748b}.modal>label,.split{margin-top:13px}.modal label{display:block}.modal label>span{display:block;margin-bottom:6px;font-size:10px;font-weight:900}.modal input,.modal select,.modal textarea{width:100%;padding:12px;border:1px solid #dce4ef;border-radius:11px;background:#fff;font-size:11px;outline:none}.modal textarea{height:72px;resize:none}.split{display:grid;grid-template-columns:1fr 1fr;gap:8px}.error{margin-top:8px;color:#e5484d;font-size:9px}.save{width:100%;height:50px;margin-top:15px;border-radius:12px;background:#173f8d;color:#fff;font-size:13px;font-weight:900}.save:disabled{background:#aab4c3}
</style>
