INSERT INTO travel_card_currencies (card_id, currency_code)
SELECT tc.id, x.currency_code
FROM travel_cards tc
         JOIN (SELECT 'USD' currency_code
               UNION ALL
               SELECT 'JPY'
               UNION ALL
               SELECT 'EUR'
               UNION ALL
               SELECT 'GBP'
               UNION ALL
               SELECT 'CNY'
               UNION ALL
               SELECT 'SGD'
               UNION ALL
               SELECT 'CAD'
               UNION ALL
               SELECT 'AUD'
               UNION ALL
               SELECT 'VND'
               UNION ALL
               SELECT 'HKD'
               UNION ALL
               SELECT 'THB'
               UNION ALL
               SELECT 'CHF'
               UNION ALL
               SELECT 'PHP'
               UNION ALL
               SELECT 'SEK'
               UNION ALL
               SELECT 'IDR'
               UNION ALL
               SELECT 'NZD'
               UNION ALL
               SELECT 'HUF'
               UNION ALL
               SELECT 'CZK'
               UNION ALL
               SELECT 'NOK'
               UNION ALL
               SELECT 'TWD'
               UNION ALL
               SELECT 'DKK'
               UNION ALL
               SELECT 'MYR'
               UNION ALL
               SELECT 'MXN'
               UNION ALL
               SELECT 'AED'
               UNION ALL
               SELECT 'TRY'
               UNION ALL
               SELECT 'PLN'
               UNION ALL
               SELECT 'SAR'
               UNION ALL
               SELECT 'ZAR'
               UNION ALL
               SELECT 'KWD'
               UNION ALL
               SELECT 'BHD'
               UNION ALL
               SELECT 'MOP'
               UNION ALL
               SELECT 'INR'
               UNION ALL
               SELECT 'KHR'
               UNION ALL
               SELECT 'BRL'
               UNION ALL
               SELECT 'MNT'
               UNION ALL
               SELECT 'EGP'
               UNION ALL
               SELECT 'QAR'
               UNION ALL
               SELECT 'KES'
               UNION ALL
               SELECT 'ILS'
               UNION ALL
               SELECT 'MMK'
               UNION ALL
               SELECT 'FJD'
               UNION ALL
               SELECT 'NPR'
               UNION ALL
               SELECT 'RON'
               UNION ALL
               SELECT 'BDT'
               UNION ALL
               SELECT 'BND'
               UNION ALL
               SELECT 'LKR'
               UNION ALL
               SELECT 'JOD'
               UNION ALL
               SELECT 'UZS'
               UNION ALL
               SELECT 'CLP'
               UNION ALL
               SELECT 'KZT'
               UNION ALL
               SELECT 'COP'
               UNION ALL
               SELECT 'TZS'
               UNION ALL
               SELECT 'PKR'
               UNION ALL
               SELECT 'RUB'
               UNION ALL
               SELECT 'LYD'
               UNION ALL
               SELECT 'DZD'
               UNION ALL
               SELECT 'ETB'
               UNION ALL
               SELECT 'OMR') x
WHERE tc.card_name IN (
                       '트래블로그 체크카드',
                       '트래블GO 체크카드'
    );

INSERT INTO travel_card_currencies (card_id, currency_code)
SELECT tc.id, x.currency_code
FROM travel_cards tc
         JOIN (SELECT 'USD' currency_code
               UNION ALL
               SELECT 'JPY'
               UNION ALL
               SELECT 'EUR'
               UNION ALL
               SELECT 'CNY'
               UNION ALL
               SELECT 'HKD'
               UNION ALL
               SELECT 'AUD'
               UNION ALL
               SELECT 'CAD'
               UNION ALL
               SELECT 'GBP'
               UNION ALL
               SELECT 'SGD'
               UNION ALL
               SELECT 'CHF'
               UNION ALL
               SELECT 'NZD'
               UNION ALL
               SELECT 'NOK'
               UNION ALL
               SELECT 'DKK'
               UNION ALL
               SELECT 'SEK'
               UNION ALL
               SELECT 'PHP'
               UNION ALL
               SELECT 'THB'
               UNION ALL
               SELECT 'TWD'
               UNION ALL
               SELECT 'IDR'
               UNION ALL
               SELECT 'AED'
               UNION ALL
               SELECT 'VND'
               UNION ALL
               SELECT 'MYR'
               UNION ALL
               SELECT 'HUF'
               UNION ALL
               SELECT 'MXN'
               UNION ALL
               SELECT 'TRY'
               UNION ALL
               SELECT 'PLN'
               UNION ALL
               SELECT 'SAR'
               UNION ALL
               SELECT 'KWD'
               UNION ALL
               SELECT 'ZAR'
               UNION ALL
               SELECT 'RUB'
               UNION ALL
               SELECT 'INR') x
WHERE tc.card_name = '위비트래블 체크카드';

INSERT INTO travel_card_currencies (card_id, currency_code)
SELECT tc.id, x.currency_code
FROM travel_cards tc
         JOIN (SELECT 'USD' currency_code
               UNION ALL
               SELECT 'JPY'
               UNION ALL
               SELECT 'EUR'
               UNION ALL
               SELECT 'CNY'
               UNION ALL
               SELECT 'HKD'
               UNION ALL
               SELECT 'AUD'
               UNION ALL
               SELECT 'CAD'
               UNION ALL
               SELECT 'GBP'
               UNION ALL
               SELECT 'SGD'
               UNION ALL
               SELECT 'CHF'
               UNION ALL
               SELECT 'NZD'
               UNION ALL
               SELECT 'NOK'
               UNION ALL
               SELECT 'DKK'
               UNION ALL
               SELECT 'SEK'
               UNION ALL
               SELECT 'PHP'
               UNION ALL
               SELECT 'THB'
               UNION ALL
               SELECT 'TWD'
               UNION ALL
               SELECT 'IDR'
               UNION ALL
               SELECT 'AED'
               UNION ALL
               SELECT 'VND'
               UNION ALL
               SELECT 'MYR'
               UNION ALL
               SELECT 'HUF'
               UNION ALL
               SELECT 'MXN'
               UNION ALL
               SELECT 'TRY'
               UNION ALL
               SELECT 'PLN'
               UNION ALL
               SELECT 'SAR'
               UNION ALL
               SELECT 'KWD'
               UNION ALL
               SELECT 'ZAR'
               UNION ALL
               SELECT 'QAR'
               UNION ALL
               SELECT 'INR'
               UNION ALL
               SELECT 'BRL'
               UNION ALL
               SELECT 'CZK'
               UNION ALL
               SELECT 'MOP'
               UNION ALL
               SELECT 'BHD'
               UNION ALL
               SELECT 'KZT'
               UNION ALL
               SELECT 'PKR'
               UNION ALL
               SELECT 'NPR'
               UNION ALL
               SELECT 'BDT'
               UNION ALL
               SELECT 'CLP'
               UNION ALL
               SELECT 'EGP'
               UNION ALL
               SELECT 'ILS'
               UNION ALL
               SELECT 'KES') x
WHERE tc.card_name = 'SOL트래블 체크카드';

-- =====================================================
-- KB국민 트래블러스 체크카드 지원 통화 56종
-- 공식 KB국민카드 환율우대 100% 통화 목록 기준
-- =====================================================

INSERT INTO travel_card_currencies (card_id, currency_code)
SELECT tc.id, x.currency_code
FROM travel_cards tc
         JOIN (SELECT 'USD' AS currency_code
               UNION ALL
               SELECT 'JPY'
               UNION ALL
               SELECT 'EUR'
               UNION ALL
               SELECT 'GBP'
               UNION ALL
               SELECT 'SGD'
               UNION ALL
               SELECT 'AUD'
               UNION ALL
               SELECT 'VND'
               UNION ALL
               SELECT 'THB'
               UNION ALL
               SELECT 'CHF'
               UNION ALL
               SELECT 'IDR'
               UNION ALL
               SELECT 'TWD'
               UNION ALL
               SELECT 'MYR'
               UNION ALL
               SELECT 'CNY'
               UNION ALL
               SELECT 'HKD'
               UNION ALL
               SELECT 'CAD'
               UNION ALL
               SELECT 'NZD'
               UNION ALL
               SELECT 'PHP'
               UNION ALL
               SELECT 'AED'
               UNION ALL
               SELECT 'DKK'
               UNION ALL
               SELECT 'EGP'
               UNION ALL
               SELECT 'HUF'
               UNION ALL
               SELECT 'INR'
               UNION ALL
               SELECT 'KHR'
               UNION ALL
               SELECT 'BRL'
               UNION ALL
               SELECT 'MNT'
               UNION ALL
               SELECT 'MXN'
               UNION ALL
               SELECT 'NOK'
               UNION ALL
               SELECT 'PLN'
               UNION ALL
               SELECT 'QAR'
               UNION ALL
               SELECT 'SAR'
               UNION ALL
               SELECT 'SEK'
               UNION ALL
               SELECT 'TRY'
               UNION ALL
               SELECT 'ZAR'
               UNION ALL
               SELECT 'BND'
               UNION ALL
               SELECT 'KZT'
               UNION ALL
               SELECT 'ARS'
               UNION ALL
               SELECT 'CLP'
               UNION ALL
               SELECT 'CZK'
               UNION ALL
               SELECT 'LKR'
               UNION ALL
               SELECT 'NPR'
               UNION ALL
               SELECT 'RON'
               UNION ALL
               SELECT 'BDT'
               UNION ALL
               SELECT 'FJD'
               UNION ALL
               SELECT 'KES'
               UNION ALL
               SELECT 'MOP'
               UNION ALL
               SELECT 'RUB'
               UNION ALL
               SELECT 'PKR'
               UNION ALL
               SELECT 'ILS'
               UNION ALL
               SELECT 'ETB'
               UNION ALL
               SELECT 'COP'
               UNION ALL
               SELECT 'MMK'
               UNION ALL
               SELECT 'BHD'
               UNION ALL
               SELECT 'JOD'
               UNION ALL
               SELECT 'LYD'
               UNION ALL
               SELECT 'OMR'
               UNION ALL
               SELECT 'KWD') x
WHERE tc.card_name = 'KB국민 트래블러스 체크카드';

