-- #179 여행 목표 등록 화면용 국가·통화 기준 데이터
-- 이미 존재하는 통화/국가는 INSERT IGNORE로 건너뜁니다.

INSERT IGNORE INTO currencies (currency_code, currency_name, symbol, unit) VALUES
('AED', '아랍에미리트 디르함', 'د.إ', 1),
('AUD', '호주 달러', '$', 1),
('BHD', '바레인 디나르', '.د.ب', 1),
('BND', '브루나이 달러', '$', 1),
('CAD', '캐나다 달러', '$', 1),
('CHF', '스위스 프랑', 'CHF', 1),
('CNY', '중국 위안화', '¥', 1),
('DKK', '덴마크 크로네', 'kr', 1),
('EUR', '유로', '€', 1),
('GBP', '영국 파운드', '£', 1),
('HKD', '홍콩 달러', '$', 1),
('IDR', '인도네시아 루피아', 'Rp', 100),
('JPY', '일본 엔', '¥', 100),
('KWD', '쿠웨이트 디나르', 'د.ك', 1),
('MYR', '말레이시아 링깃', 'RM', 1),
('NOK', '노르웨이 크로네', 'kr', 1),
('NZD', '뉴질랜드 달러', '$', 1),
('SAR', '사우디아라비아 리얄', '﷼', 1),
('SEK', '스웨덴 크로나', 'kr', 1),
('SGD', '싱가포르 달러', '$', 1),
('THB', '태국 바트', '฿', 1),
('USD', '미국 달러', '$', 1);

INSERT IGNORE INTO countries (country_name, currency_id, time_zone) VALUES
('아랍에미리트', (SELECT id FROM currencies WHERE currency_code = 'AED'), 'Asia/Dubai'),
('호주', (SELECT id FROM currencies WHERE currency_code = 'AUD'), 'Australia/Sydney'),
('바레인', (SELECT id FROM currencies WHERE currency_code = 'BHD'), 'Asia/Bahrain'),
('브루나이', (SELECT id FROM currencies WHERE currency_code = 'BND'), 'Asia/Brunei'),
('캐나다', (SELECT id FROM currencies WHERE currency_code = 'CAD'), 'America/Toronto'),
('스위스', (SELECT id FROM currencies WHERE currency_code = 'CHF'), 'Europe/Zurich'),
('중국', (SELECT id FROM currencies WHERE currency_code = 'CNY'), 'Asia/Shanghai'),
('덴마크', (SELECT id FROM currencies WHERE currency_code = 'DKK'), 'Europe/Copenhagen'),
('프랑스', (SELECT id FROM currencies WHERE currency_code = 'EUR'), 'Europe/Paris'),
('영국', (SELECT id FROM currencies WHERE currency_code = 'GBP'), 'Europe/London'),
('홍콩', (SELECT id FROM currencies WHERE currency_code = 'HKD'), 'Asia/Hong_Kong'),
('인도네시아', (SELECT id FROM currencies WHERE currency_code = 'IDR'), 'Asia/Jakarta'),
('일본', (SELECT id FROM currencies WHERE currency_code = 'JPY'), 'Asia/Tokyo'),
('쿠웨이트', (SELECT id FROM currencies WHERE currency_code = 'KWD'), 'Asia/Kuwait'),
('말레이시아', (SELECT id FROM currencies WHERE currency_code = 'MYR'), 'Asia/Kuala_Lumpur'),
('노르웨이', (SELECT id FROM currencies WHERE currency_code = 'NOK'), 'Europe/Oslo'),
('뉴질랜드', (SELECT id FROM currencies WHERE currency_code = 'NZD'), 'Pacific/Auckland'),
('사우디아라비아', (SELECT id FROM currencies WHERE currency_code = 'SAR'), 'Asia/Riyadh'),
('스웨덴', (SELECT id FROM currencies WHERE currency_code = 'SEK'), 'Europe/Stockholm'),
('싱가포르', (SELECT id FROM currencies WHERE currency_code = 'SGD'), 'Asia/Singapore'),
('태국', (SELECT id FROM currencies WHERE currency_code = 'THB'), 'Asia/Bangkok'),
('미국', (SELECT id FROM currencies WHERE currency_code = 'USD'), 'America/New_York');
