<script setup>
import { useRouter } from 'vue-router';import BottomNav from '@/components/common/BottomNav.vue';import { useFinancialProductsStore } from '@/stores/financialProducts'
const router=useRouter();const products=useFinancialProductsStore();const money=(v)=>`${Number(v).toLocaleString('ko-KR')}원`
const rows=[
  {label:'해외 결제 수수료',value:(c)=>c.overseasFee?`${c.overseasFee}%`:'무료',best:(c)=>c.overseasFee===0},
  {label:'재환전 수수료',value:(c)=>`${c.reloadFee}%`,best:(c)=>c.reloadFee===Math.min(...products.comparedCards.map(x=>x.reloadFee))},
  {label:'충전 한도',value:(c)=>money(c.maxCharge)},
  {label:'ATM 출금',value:(c)=>`월 ${money(c.atmLimit)}`},
  {label:'지원 통화',value:(c)=>`${c.currencies}개`,best:(c)=>c.currencies===Math.max(...products.comparedCards.map(x=>x.currencies))},
  {label:'교통카드',value:(c)=>c.transit?'지원':'미지원',best:(c)=>c.transit},
]
</script>
<template><main class="page"><div class="shell"><header><button @click="router.back()">‹</button><h1>카드 비교</h1></header><div class="heading"><b>비교할 카드 선택</b><span>{{ products.comparedCards.length }}/3 선택</span></div><section class="selected"><article v-for="card in products.comparedCards" :key="card.id"><i :style="{background:card.color}">{{ card.code }}</i><b>{{ card.company }}</b><button @click="products.toggleCompare(card.id)">×</button></article><button v-if="products.comparedCards.length<3" class="add" @click="router.push('/financial/cards')"><strong>＋</strong><small>카드 추가</small></button></section><template v-if="products.comparedCards.length"><div class="table-title"><h2>핵심 혜택 비교</h2><span>우수 조건은 파란색으로 표시</span></div><section class="table"><div class="head"><b>비교 항목</b><b v-for="card in products.comparedCards" :key="card.id">{{ card.company }}</b></div><div v-for="row in rows" :key="row.label" class="row"><b>{{ row.label }}</b><span v-for="card in products.comparedCards" :key="card.id" :class="{best:row.best?.(card)}">{{ row.value(card) }}</span></div></section></template><section v-else class="empty"><b>비교할 카드를 선택해 주세요</b><button @click="router.push('/financial/cards')">카드 선택하기</button></section><button class="cta" :disabled="products.comparedCards.length<2" @click="router.push(`/financial/cards/${products.comparedCards[0]?.id}`)">선택한 카드 상세 보기</button><BottomNav/></div></main></template>
<style scoped>
.page{min-height:100vh;background:#e7ecf4;color:#10192d}.shell{width:min(100%,390px);min-height:100vh;margin:auto;padding:52px 18px 100px;background:#f7f5ef}header{display:flex;align-items:center;margin-bottom:20px}header button{width:28px;font-size:25px}header h1{flex:1;padding-right:28px;text-align:center;font-size:18px}.heading{display:flex;justify-content:space-between;align-items:center}.heading b{font-size:11px}.heading span{padding:6px 10px;border-radius:12px;background:#1472ee;color:#fff;font-size:8px}.selected{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.selected article,.add{position:relative;display:grid;min-height:74px;place-content:center;justify-items:center;border:1px solid #dce4ef;border-radius:12px;background:#fff}.selected i{display:grid;width:34px;height:25px;place-items:center;border-radius:6px;color:#fff;font-size:7px;font-style:normal;font-weight:900}.selected b{margin-top:6px;font-size:8px}.selected article button{position:absolute;top:4px;right:6px;color:#9ba6b5}.add strong{color:#1472ee;font-size:20px}.add small{color:#4972a8;font-size:7px}.table-title{display:flex;justify-content:space-between;margin:22px 1px 9px}.table-title h2{font-size:12px}.table-title span{color:#69809e;font-size:7px}.table{overflow:hidden;border:1px solid #dfe5ed;border-radius:14px;background:#fff}.head,.row{display:grid;grid-template-columns:88px repeat(3,1fr)}.head{background:#f3f6fa}.head b,.row>*{padding:11px 5px;text-align:center;font-size:7px}.head b:first-child,.row>b{text-align:left}.row{border-top:1px solid #edf0f4}.row>b{color:#728095}.row span{font-weight:800}.row .best{color:#1472ee}.empty{padding:50px 20px;text-align:center}.empty b{display:block;font-size:11px}.empty button{margin-top:13px;padding:10px 15px;border-radius:9px;background:#173f8d;color:#fff;font-size:8px}.cta{width:100%;margin-top:15px;padding:14px;border-radius:11px;background:#173f8d;color:#fff;font-weight:900}.cta:disabled{background:#aab4c3}
</style>
