<script setup>
import { useRouter } from 'vue-router'
import BottomNav from '@/components/common/BottomNav.vue'
import { useMypageStore } from '@/stores/mypage'
const router=useRouter(); const store=useMypageStore(); const money=n=>Number(n).toLocaleString('ko-KR')+'원'
</script>
<template><main class="page"><header><button @click="router.back()">‹</button><h1>금융 프로필</h1><button class="edit" @click="router.push('/mypage/financial-profile/edit')">수정</button></header>
<section class="ticket"><small>MONTHLY INCOME PASS</small><div><span>월 급여 총액<strong>{{ money(store.totalIncome) }}</strong></span><span>급여일<b>매월 {{ store.incomes[0]?.payDay || '-' }}일</b></span></div><p>급여 {{ store.incomes.length }}건 · 입금 계좌 연결 완료</p></section>
<section v-for="income in store.incomes" :key="income.id" class="card"><h2>월 수입 정보</h2><dl><div><dt>급여명</dt><dd>{{ income.name }}</dd></div><div><dt>급여일</dt><dd>매월 {{ income.payDay }}일</dd></div><div><dt>월 급여액</dt><dd class="blue">{{ money(income.amount) }}</dd></div><div><dt>메모</dt><dd>{{ income.memo || '-' }}</dd></div><div><dt>입금 계좌</dt><dd>{{ income.account }}</dd></div></dl></section>
<aside>✈️ <span><b>등록한 월 수입으로 여행 저축 가능 금액을 계산해요</b><small>급여 정보는 언제든 수정할 수 있어요.</small></span></aside><button class="add" @click="router.push('/mypage/financial-profile/edit')">＋ 급여 정보 추가</button><BottomNav/></main></template>
<style scoped>.page{min-height:100vh;padding:0 20px 92px;background:#f8f6f1;color:#10192d}.page>header{display:grid;height:61px;grid-template-columns:45px 1fr 45px;align-items:end;padding-bottom:16px}.page>header button:first-child{display:grid;width:36px;height:36px;place-items:center;border-radius:12px;background:#fff;color:#193d82;font-size:24px;font-weight:700;box-shadow:0 5px 16px rgba(36,72,117,.07)}.page h1{text-align:center;font-size:21px;font-weight:900}.edit{color:#1670ef!important;font-size:13px!important;text-align:right!important}.ticket{position:relative;padding:22px;border-radius:22px;background:linear-gradient(135deg,#12347c,#1b56b0);color:#fff}.ticket small{color:#bdd0f4;font-size:9px;letter-spacing:1px}.ticket>div{display:flex;justify-content:space-between;margin-top:19px}.ticket span{color:#bdcae1;font-size:10px}.ticket strong,.ticket b{display:block;margin-top:8px;color:#fff;font-size:25px}.ticket b{color:#57c9ff;font-size:15px}.ticket p{margin-top:18px;padding-top:13px;border-top:1px dashed #ffffff55;color:#cedaf0;font-size:9px}.card{margin-top:14px;padding:20px;border:1px solid #e2e6ec;border-radius:22px;background:#fff}.card h2{font-size:15px;font-weight:900}.card dl{margin-top:13px}.card dl div{display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid #edf0f3;font-size:11px}.card dl div:last-child{border:0}.card dt{color:#8a97a9}.card dd{max-width:65%;font-weight:700;text-align:right}.blue{color:#126df0}aside{display:flex;gap:12px;margin-top:14px;padding:17px;border-radius:17px;background:#e9f3ff;font-size:19px}aside span>*{display:block}aside b{font-size:11px}aside small{margin-top:6px;color:#77879d;font-size:9px}.add{width:100%;margin-top:12px;padding:14px;border:1px dashed #d3dce8;border-radius:13px;background:#fff;color:#66758b;font-size:12px}</style>
