<script setup>
import { ref } from 'vue'; import { useRouter } from 'vue-router'; import { useMypageStore } from '@/stores/mypage'
const router=useRouter(), store=useMypageStore(); const items=ref(store.incomes.map(i=>({...i})))
const add=()=>items.value.push({id:Date.now(),name:'',payDay:25,amount:0,memo:'',account:'하나은행 급여계좌 · ****4821'})
const valid=()=>items.value.length&&items.value.every(i=>i.name.trim()&&i.payDay>=1&&i.payDay<=31&&i.amount>=0)
function submit(){if(!valid())return;store.saveIncomes(items.value);router.push('/mypage/financial-profile')}
</script>
<template><main class="page"><header><button @click="router.back()">‹</button><h1>금융 프로필 수정</h1><span/></header><section class="summary"><small>등록된 월 수입</small><strong>{{ items.reduce((s,i)=>s+Number(i.amount||0),0).toLocaleString() }}원</strong><b>{{ items.length }}건</b></section><section v-for="(item,index) in items" :key="item.id" class="card"><div><h2>급여 정보 {{ index+1 }}</h2><button v-if="items.length>1" @click="items.splice(index,1)">삭제</button></div><label>급여명<input v-model="item.name" placeholder="급여명을 입력해 주세요"></label><div class="row"><label>급여일<input v-model.number="item.payDay" type="number" min="1" max="31"></label><label>월 급여액<input v-model.number="item.amount" type="number" min="0"></label></div><label>메모<input v-model="item.memo" placeholder="선택사항"></label><label>입금 계좌<select v-model="item.account"><option>하나은행 급여계좌 · ****4821</option><option>KB국민은행 여행통장 · ****1234</option></select></label></section><button class="add" @click="add">＋ 급여 정보 추가</button><button class="cta" :disabled="!valid()" @click="submit">수정 내용 저장</button></main></template>
<style scoped>.page{min-height:100vh;padding:0 20px 110px;background:#f8f6f1;color:#10192d}.page>header{display:grid;height:90px;grid-template-columns:40px 1fr 40px;align-items:end;padding-bottom:16px}.page>header button{font-size:28px;text-align:left}.page h1{text-align:center;font-size:20px;font-weight:900}.summary{position:relative;padding:20px;border-radius:18px;background:#173d87;color:#fff}.summary>*{display:block}.summary small{color:#b9c9e7;font-size:9px}.summary strong{margin-top:8px;font-size:26px}.summary b{position:absolute;right:20px;bottom:22px;color:#6ed0ff;font-size:12px}.card{margin-top:13px;padding:18px;border:1px solid #e0e5ec;border-radius:18px;background:#fff}.card>div:first-child{display:flex;justify-content:space-between}.card h2{font-size:14px;font-weight:900}.card button{color:#e5484d;font-size:10px}.card label{display:block;margin-top:14px;color:#68768b;font-size:9px}.card input,.card select{width:100%;margin-top:6px;padding:12px;border:1px solid #dce3ec;border-radius:10px;color:#10192d;font-size:11px}.row{display:grid!important;grid-template-columns:1fr 1fr;gap:9px}.add{width:100%;margin-top:13px;padding:14px;border:1px dashed #a9bddd;border-radius:12px;color:#176ff2}.cta{position:fixed;right:max(calc((100vw - 390px)/2 + 20px),20px);bottom:25px;left:max(calc((100vw - 390px)/2 + 20px),20px);height:54px;border-radius:14px;background:#173d87;color:#fff;font-weight:900}.cta:disabled{background:#aab4c5}</style>
