db.url=jdbc:log4jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tripass}?useSSL=false&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&preserveInstants=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
db.username=${DB_USERNAME:root}
db.password=${DB_PASSWORD:1234}